import "./style.css";

const assets = [
  {
    id: "1-ACC",
    name: "Monitor Acer 120Hz",
    category: "Prislusenstvi",
    type: "Monitor",
    status_id: "issue",
    status_text: "Nefunkční",
  },
  {
    id: "2-ACC",
    name: "Klavesnice Logitech",
    category: "Prislusenstvi",
    type: "Klavesnice",
    status_id: "ok",
    status_text: "V pořádku",
  },
  {
    id: "3-ACC",
    name: "Myš Razer",
    category: "Prislusenstvi",
    type: "Mys",
    status_id: "ok",
    status_text: "V pořádku",
  },
  {
    id: "4-ACC",
    name: "Sluchátka HyperX",
    category: "Prislusenstvi",
    type: "Sluchatka",
    status_id: "pending",
    status_text: "Fasování",
  },
  {
    id: "5-ACC",
    name: "Webkamera Logitech",
    category: "Prislusenstvi",
    type: "Webkamera",
    status_id: "ok",
    status_text: "V pořádku",
  },
  {
    id: "6-ACC",
    name: "Reproduktory Bose",
    category: "Prislusenstvi",
    type: "Reproduktory",
    status_id: "ok",
    status_text: "V pořádku",
  },
  {
    id: "7-ACC",
    name: "Externí pevný disk Seagate",
    category: "Prislusenstvi",
    type: "Pevny disk",
    status_id: "issue",
    status_text: "Nefunkční",
  },
  {
    id: "8-ACC",
    name: "USB flash disk SanDisk",
    category: "Prislusenstvi",
    type: "Flash disk",
    status_id: "ok",
    status_text: "V pořádku",
  },
  {
    id: "9-ACC",
    name: "Grafická karta NVIDIA",
    category: "Prislusenstvi",
    type: "Graficka karta",
    status_id: "issue",
    status_text: "Nefunkční",
  },
  {
    id: "10-ACC",
    name: "Zvuková karta Creative Sound Blaster",
    category: "Prislusenstvi",
    type: "Zvukova karta",
    status_id: "pending",
    status_text: "Fasování",
  },
  {
    id: "11-ACC",
    name: "Kancelarske kresla",
    category: "Nabytek",
    type: "Kresla",
    status_id: "ok",
    status_text: "V pořádku",
  },
  {
    id: "12-ACC",
    name: "Kancelarske stoly",
    category: "Nabytek",
    type: "Stoly",
    status_id: "pending",
    status_text: "Fasování",
  },
  {
    id: "13-ACC",
    name: "Kancelarske skrine",
    category: "Nabytek",
    type: "Skrine",
    status_id: "issue",
    status_text: "Nefunkční",
  },
  {
    id: "14-ACC",
    name: "Kancelarske zidle",
    category: "Nabytek",
    type: "Zidle",
    status_id: "ok",
    status_text: "V pořádku",
  },
  {
    id: "15-ACC",
    name: "Kancelarske policky",
    category: "Nabytek",
    type: "Policky",
    status_id: "ok",
    status_text: "V pořádku",
  },
  {
    id: "16-ACC",
    name: "Kancelarske konference stoly",
    category: "Nabytek",
    type: "Konference stoly",
    status_id: "issue",
    status_text: "Nefunkční",
  },
  {
    id: "17-ACC",
    name: "Pristupova karta",
    category: "Bezpecnost",
    type: "Pristupova karta",
    status_id: "issue",
    status_text: "Nefunkční",
  },
  {
    id: "18-ACC",
    name: "Sluzebni telefon",
    category: "Prislusenstvi",
    type: "Telefon",
    status_id: "ok",
    status_text: "V pořádku",
  },
  {
    id: "19-ACC",
    name: "Sluzebni auto",
    category: "Doprava",
    type: "Auto",
    status_id: "pending",
    status_text: "Fasování",
  },
];

const assetContainer = document.getElementById("asset-grid");
